### PR TITLE
Android set cookie

### PR DESCRIPTION
**Pull request by harrydema**
Functionality to set cookies on android.

### CODE REVIEW

**Comment by safaiyeh** [comment]
@harrydema check if the code I pushed worked.

I found this article which helped me out: https://medium.com/@ericluapp/something-might-be-confused-about-cookiemanager-setcookie-422e6e28aacf

On my end:
Screen Shot 2019-12-16 at 9 15 42 PM

**Comment by harrydema** [comment]
I don't think this is the way it should work.

In your commit you are just setting a name and a value, the cookie format has path, expiration, domain, etc. We should leave the iteration as I did.

Besides, can you show the javascript code? I want to see how those console.log are printed.

The idea of accessing the cookie manager directly might be a solution.

By the way, the get(url) method of this library just returns one cookie, this should be modified to retrieve all thee cookies set to given url.

Should we set as key the origin or the domain for set method??

**Comment by safaiyeh** [comment]
I agree with the iteration.

```JavaScript
const newCookie = {
    name: 'myCookie',
    value: 'myValue',
    domain: 'http://example.com',
    origin: 'some origin',
    path: '/',
    version: '1',
    expiration: '2015-05-30T12:30:00.00-05:00',
    random: 'HELLO'
  };

  const newCookie2= {
    name: 'test',
    value: 'myValue',
    domain: 'http://example.com',
    origin: 'some origin',
    path: '/',
    version: '1',
    expiration: '2015-05-30T12:30:00.00-05:00',
    random1: 'HELLO'
  };
  
  
  
  CookieManager.set(newCookie, true)
    .then((res) => {
      console.log(res);
      CookieManager.set(newCookie2, true)
      .then((res) => {
        console.log(res);
        CookieManager.get('http://example.com', true)
        .then((res) => {
          console.log('CookieManager.get from webkit-view =>', res);
          // => 'user_session=abcdefg; path=/;'
        });
      })
    });
```

Android Docs: https://developer.android.com/reference/android/webkit/CookieManager.html#setCookie(java.lang.String,%20java.lang.String)

The issue is that the cookie string does not take multiple attributes if you check out the article.
Screen Shot 2019-12-17 at 8 12 59 AM

**Comment by safaiyeh** [comment]
I'll play around with it more tonight.

**Comment by safaiyeh** [comment]
Another solution could be to use Java's CookieManager instead of webkit.

https://stackoverflow.com/a/23365081

**Comment by KingAmo** [comment]
any update on this PR?

**Pull request closed without merging**
